name: MediaTopPlugin
version: ${project.version}
main: gg.steve.mc.deezer.mt.MediaTopPlugin
api-version: 1.17
authors: [ stevegoodhill ]
description: MediaTop plugin developer for Deezer by stevegoodhill.
